554-🎨⭐- Add Language choice for First Screen
redDwarf03/archethic_mobile_wallet pull request #644
Opened 2023-01-26 21:27 UTC by Esquimor

Link to this issue: [#554](https://github.com/archethic-foundation/archethic-wallet/issues/554)

What I have done:

- Refacto: intro_welcom.dart
- Add a button to change language
- Create the component "BannerConnectivityNotAvailable" to use the same component everywhere.

@redDwarf03 you can review

2023-01-26 21:59 UTC, redDwarf03 requested changes

2023-01-26 21:59 UTC, redDwarf03 commented on lib/ui/widgets/components/banner_connectivity_not_available.dart
> +class BannerConnectivityNotAvailable extends ConsumerWidget {
Good proposal. Just perhaps instead this new widget, add in MainAppBarIconNetworkWarning a new optional  param "Alignment alignment". By default, alignment could be center but in intro pages, you can pass ``Alignment.topRight``.

2023-01-26 21:59 UTC, redDwarf03 commented on lib/ui/widgets/components/banner_connectivity_not_available.dart
> +class BannerConnectivityNotAvailable extends ConsumerWidget {
And rename ``MainAppBarIconNetworkWarning``to ``IconNetworkWarning`` and move to your folder proposal ``lib/ui/widgets/components``

2023-01-26 21:59 UTC, redDwarf03 commented on lib/ui/views/intro/intro_welcome.dart
> +class _WelcomTextFirst extends ConsumerWidget {
please, "WelcomeTextFirst"

2023-01-26 21:59 UTC, redDwarf03 commented on lib/ui/views/intro/intro_welcome.dart
> +class _WelcomTextSecond extends ConsumerWidget {
please, "WelcomeTextSecond"

2023-01-26 21:59 UTC, redDwarf03 commented on lib/ui/views/intro/intro_welcome.dart
> +          color: Colors.blue,
This color is not referenced in the app. Perhaps use theme.iconDrawer

2023-01-26 21:59 UTC, redDwarf03 commented on lib/ui/views/intro/intro_welcome.dart
> +class _CGU extends ConsumerWidget {
Continue your idea of structuration: separate CGU and version info.
So don't use isConnectivityAvailable in param but directly a condition to display or not the widget ``_CGU``

2023-01-26 21:59 UTC, redDwarf03 commented on lib/ui/views/intro/intro_welcome.dart
> +class _ButtonAction extends ConsumerWidget {
Could you change the name of ``outline``param with ``enabled`` please
And the button import should have ``Dimens.buttonBottomDimens`` and create button ``  Dimens.buttonTopDimens``
I prefer you let buttons like before (perhaps in this case, you are going too far in structuration ;) )

2023-01-27 20:50 UTC, Esquimor commented
I have resolve all the changes.

Also, I have put the language icon in an AppBar. Can you tell me if it suit ? @redDwarf03

2023-01-31 10:10 UTC, redDwarf03 commented
i changed the UI:
- i add the warning connectivity icon in the appbar 
- i fix the background displayed

Thx for contribution @Esquimor 
i merge the PR

2023-01-31 10:10 UTC, redDwarf03 approved these changes

2023-01-31 10:10 UTC, merged